spring:
  profiles:
    include:
      - @generic.profile.name@
      - @with-actuator.profile.name@
      - @with-security.profile.name@

app:
  property: "from default profile"

---
spring.profiles: generic

app:
  property: "from generic profile"

---
spring.profiles: with-actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  property: "from with-actuator profile"

---
spring.profiles: with-security

app:
  property: "from with-security profile"

management:
  server:
    ssl:
      enabled: false